### ISSUE TITLE
Installer for your client.

### ISSUE THREAD

**Issue by TwoThreeTwo** [ThnksCJ/InstallerForJava#1]
I had to stop working on my client as I fucked up some stuff with MySql and NetBeans, so the database is not working anymore. But, I saw a client aka arsie mod, and it's using swing and shit sorta like the phobos new base thing. And I know you're prob still trying to figure out some stuff but. You can take some ideas from it if you want to lol.
[installer.zip](https://github.com/ThnksCJ/InstallerForJava/files/8277580/installer.zip)
https://github.com/maywr/arsie-mod-beta 
This is where the info is, obviously I don't recommend skidding it but it's 'decent' for a client that doesnt use a loader lol.

**Comment by ThnksCJ** [comment]
lol ive only just seen the message, i might come back to it but ive moved onto another project
